/**
 * Generated by chatGPT
 * prompt:
 * give me a mui component using Skeleton
 * for the loading state of RecipeCard
 *
 * did some tweaks on width to better match
 */
import { Card, CardActions, CardContent, Skeleton } from "@mui/material";

export default function RecipeCardSkeleton() {
  return (
    <Card>
      <Skeleton variant="rectangular" width="100%" height={180} />
      <CardContent>
        <Skeleton variant="text" sx={{ fontSize: "1.5rem" }} />
        <Skeleton variant="text" sx={{ fontSize: "1rem" }} />
        <Skeleton variant="text" width="60%" />
      </CardContent>
      <CardActions>
        <Skeleton variant="rectangular" width={60} height={36} />
        <Skeleton variant="rectangular" width={60} height={36} />
      </CardActions>
      <Skeleton
        variant="rectangular"
        width="90%"
        height={36}
        style={{ margin: 10 }}
      />
    </Card>
  );
}
