/**
 * Generated by chatGPT
 * prompt:
 * i need a ts function to mock data fetching in a react component
 */
export function mockFetch<T>(data: T, delay: number = 1000): Promise<T> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(data);
    }, delay);
  });
}
